### PR TITLE
Fix #253: add AdcStart() before each AdcGetValue()

### LINKED ISSUE #253: ReadAnalog fails
I am using MCCI 4610 and see "?CatenaStm32L0::ReadAnalog(3): CatenaStm32L0_ReadAnalog() failed (5)" messages as in https://github.com/mcci-catena/Catena-Arduino-Platform/issues/125

This happens not all the time and seems to start happening only after some time.

Board Version: 2.7.0
System Clock: 24 MHz

Libraries:
| URL | Commit | Commit Date |
| --- | -----  | ----------- |
| https://github.com/mcci-catena/arduino-lmic.git  | 6fe04ec | Tue, 12 May 2020 09:16:47 -0400  |
| https://github.com/mcci-catena/arduino-lorawan.git  | 4bc0d48 | Sat, 9 May 2020 12:38:28 -0400  |
| https://github.com/mcci-catena/Catena-Arduino-Platform.git  | 92019ca | Tue, 12 May 2020 01:34:08 -0400  |
| https://github.com/mcci-catena/Catena-mcciadk.git  | a428006 | Sat, 21 Dec 2019 20:45:26 -0500  |
| https://github.com/mcci-catena/MCCI_FRAM_I2C.git  | f0a5ea5 | Sat, 21 Dec 2019 16:17:01 -0500  |

I read the battery voltage on every iteration (after waking up from deep sleep):
```
  // vBat
  int vbat_mv = (int)(gCatena.ReadVbat() * 1000.0f);
  gCatena.SafePrintf("vBat:    %d mV\n", vbat_mv);
```
Attached is the log with the relevant lines.
[ReadAnalog-errors.txt](https://github.com/mcci-catena/Catena-Arduino-Platform/files/4763260/ReadAnalog-errors.txt)

### PR DESCRIPTION
**Pull request by dhineshkumarmcci**
This pull-reuqest includes:

- ADC code fix for ReadAnalog failure #253 
- Update in Version number (last field)
- Update in Revision history in README

### CODE REVIEW

File: src/lib/stm32/stm32l0/CatenaStm32L0_ReadAnalog.cpp [hunk 1]
```diff
@@ -163,17 +163,22 @@ bool McciCatena::CatenaStm32L0_ReadAnalog(
 		ADC1->SMPR = ADC_SMPR_SMPR;
 		ADC->CCR = ADC_CCR_VREFEN;
 
-		/* start ADC, which will take 2 readings */
+		/* start ADC, before each readings */
```
Comment (terrillmoore) [inline src/lib/stm32/stm32l0/CatenaStm32L0_ReadAnalog.cpp:166]: "before each reading" not "readings".

Comment (dhineshkumarmcci) [reply src/lib/stm32/stm32l0/CatenaStm32L0_ReadAnalog.cpp]: @terrillmoore made the suggested change.
